### ISSUE TITLE
YouTube Tutorial about Networking

### ISSUE THREAD

**Issue by rebeloper** [freshOS/Networking#35]
Hi there 👋,
I've been using Networking for a while, and I love it. A lot. So I have decided to create a YouTube video on my channel teaching my 17.5K subscribers how easy it is to use Networking. 

You can take a look at it here: https://youtu.be/RM5uKTBr20c

If you like the video tutorial consider adding it to your README. You may also use my video thumbnail:

![Alamofire-e](https://user-images.githubusercontent.com/2488011/135862137-fa5de700-fd1f-4607-9de0-7c5e64111a1c.jpg)

Thanks for creating Networking and freshOS,
Alex

**Comment by s4cha** [comment]
Alex, 

This is brilliant !
I agree 100% with you on the fact that many people still use Alamofire, “just because”, and that it’s overkill in most cases.
I am really glad you like it and super pumped that you made such a wonderful video ! I am going to add the link to the readme for sure.

If you have any issues, improvement ideas, or whatever that comes to mind to make the library better, don’t hesitate to share :)

Have a fantastic day,

Sacha

**Comment by rebeloper** [comment]
Awesome! Thanks for adding the video in the README. There's a typo in `tutorial` :)

Keep up the good work,

Alex
